"""add razorpay webhook events

Revision ID: 37e3c1135adb
Revises: 9cdc69381336
Create Date: 2026-08-22 21:46:37.005314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e3c1135adb'
down_revision: Union[str, Sequence[str], None] = '9cdc69381336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razorpay_webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_razorpay_webhook_events_event_id'), 'razorpay_webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_razorpay_webhook_events_event_id'), table_name='razorpay_webhook_events')
    op.drop_table('razorpay_webhook_events')
    # ### end Alembic commands ###
