"""add razorpay upi qr fields

Revision ID: 82d7875debf5
Revises: 37e3c1135adb
Create Date: 2026-08-26 01:39:30.857894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d7875debf5'
down_revision: Union[str, Sequence[str], None] = '37e3c1135adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_qr_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_qr_content', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('razorpay_qr_image_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_payments_razorpay_qr_id'), 'payments', ['razorpay_qr_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_razorpay_qr_id'), table_name='payments')
    op.drop_column('payments', 'razorpay_qr_image_url')
    op.drop_column('payments', 'razorpay_qr_content')
    op.drop_column('payments', 'razorpay_qr_id')
    # ### end Alembic commands ###
