"""add razorpay payment fields

Revision ID: 9cdc69381336
Revises: 3e8cb5895dd8
Create Date: 2026-08-22 20:45:47.537855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdc69381336'
down_revision: Union[str, Sequence[str], None] = '3e8cb5895dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('razorpay_signature', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_column('payments', 'razorpay_signature')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_order_id')
    # ### end Alembic commands ###
