"""complete inventory management

Revision ID: bf7b7f44137a
Revises: 82d7875debf5
Create Date: 2026-08-29 10:20:24.467236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf7b7f44137a'
down_revision: Union[str, Sequence[str], None] = '82d7875debf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('inventory', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('inventory', 'unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_inventory_menu_item_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_menu_item_id'), 'inventory', ['menu_item_id'], unique=True)
    op.drop_column('inventory', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_inventory_menu_item_id'), table_name='inventory')
    op.create_index(op.f('ix_inventory_menu_item_id'), 'inventory', ['menu_item_id'], unique=False)
    op.alter_column('inventory', 'unit',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('inventory', 'updated_at')
    op.drop_column('inventory', 'created_at')
    # ### end Alembic commands ###
